--Group By Claus

--1] WAQTD MIN SALARY IN EACH DEPTNO.
-- SELECT MIN(SAL),DEPTNO
-- FROM SCOTT.EMP
-- GROUP BY DEPTNO

--2] WAQTD AVERAGE SALARY OF EMP’S IN EACH JOB. 
-- SELECT AVG(SAL),JOB
-- FROM SCOTT.EMP
-- GROUP BY JOB;

-- 3] WAQTD NUMBER OF EMP’S IN EACH DEPARTMENT IF THE EMP’S 
-- ARE EARNING MORE THAN RS.2000. 
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE SAL>2000
-- GROUP BY DEPTNO;

-- 4] WAQTD NUMBER OF EMP’S WORKING IN EACH DEPT EXCEPT 
-- ‘PRESIDENT’.
-- SELECT COUNT(*) NO_OF_EMPS,DEPTNO
-- FROM SCOTT.EMP
-- WHERE ENAME!='PRESIDENT'
-- GROUP BY DEPTNO;

-- 5] WAQTD NUMBER OF EMP’S WORKING AS ‘MANAGER’ IN EACH 
-- DEPT. 
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE JOB='MANAGER'
-- GROUP BY DEPTNO;

-- 6] WAQTD AVG SAL NEEDED TO PAY TO ALL THE EMP’S EXCLUDING 
-- THE EMP’S WORKING IN DEPT NO 20 IN EACH JOB. 
-- SELECT AVG(SAL),JOB
-- FROM SCOTT.EMP
-- WHERE DEPTNO != 20
-- GROUP BY JOB;

-- 7] WAQTD NUMBER OF EMP’S HAVING CHARACTER ‘A’ IN THEIR 
-- NAME IN EACH JOB.
-- SELECT COUNT(*), JOB
-- FROM SCOTT.EMP
-- WHERE ENAME LIKE '%A%'
-- GROUP BY JOB;

-- 8] WAQTD NUMBER OF EMP’S WORKING AS A CLERK IN EACH 
-- DEPARTMENT. 
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE JOB='CLERK'
-- GROUP BY DEPTNO;

-- 9] WAQTD NUMBER OF EMP’S HIRED IN THE YEAR 1981 IN EACH 
-- DEPARTMENT. 
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE HIREDATE LIKE '%81'
-- GROUP BY DEPTNO;

-- 10] WAQTD NUMBER OF EMP’S WARNING LESS THAN 1OOO IN EACH 
-- DEPARTMENT.
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE SAL<1000
-- GROUP BY DEPTNO;

-- 11] WAQTD NUMBER OF EMP’S EARNING 3000 RS IN EACH 
-- DEPARTMENT.
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE SAL=3000
-- GROUP BY DEPTNO;

-- 12] WAQTD MAXIMUM SALARY GIVEN TO THE EMP WORKING AS A 
-- CLERK IN EACH DEPT. 
-- SELECT MAX(SAL),DEPTNO
-- FROM SCOTT.EMP
-- WHERE JOB='CLERK'
-- GROUP BY DEPTNO;

-- 13] WAQTD NUMBER OF EMP’S HIRED IN THE MONTH OF FEBRUARY 
-- IN EACH JOB.
-- SELECT COUNT(*),JOB
-- FROM SCOTT.EMP
-- WHERE HIREDATE LIKE '%FEB%'
-- GROUP BY JOB;

-- 14] WAQTD NUMBER OF EMP’S WORKING AS PRESIDENT OR ANALYST 
-- AND EARNING MORE THAN 2000 IN EACH DEPARTMENT.
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE JOB IN ('PRESIDENT','ANALYST') AND
--     SAL>2000
-- GROUP BY DEPTNO;

-- 15] WAQTD NUMBER OF EMP’S WORKING IN EACH DEPT EXCEPT 
-- -- PRESIDENT.
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE JOB!='PRESIDENT'
-- GROUP BY DEPTNO;

-- 16] WAQTD TOTAL SALARY NEEDED TO PAY ALL THE EMP’S IN EACH JOB
-- SELECT SUM(SAL),JOB
-- FROM SCOTT.EMP
-- GROUP BY JOB;

-- 17] WAQTD AVERAGE SALARY NEEDED TO PAY ALL THE EMP’S IN 
-- EACH DEPT EXCLUDING THE EMP’S OF DEPTNO 20. 
-- SELECT AVG(SAL),DEPTNO
-- FROM SCOTT.EMP
-- WHERE DEPTNO!=20
-- GROUP BY DEPTNO;

-- 18] WAQTD NUMBER OF EMP’S HAVING CHARACTER ‘A’ IN THEIR 
-- NAMES IN EACH JOB.
-- SELECT COUNT(*),JOB
-- FROM SCOTT.EMP
-- WHERE ENAME LIKE '%A%'
-- GROUP BY JOB;

-- 19] WAQTD NUMBER OF EMP’S AND AVG SAL NEEDED TO PAY THE 
-- EMP’S WHOSE SAL GREATER THAN 2000 IN EACH DEPT. 
-- SELECT COUNT(*),AVG(SAL),DEPTNO
-- FROM SCOTT.EMP
-- WHERE SAL>2000
-- GROUP BY DEPTNO;

-- 20] WAQTD NUMBER OF EMP’S AND TOTAL SAL GIVEN TO ALL THE 
-- SALESMAN IN EACH DEPT
-- SELECT COUNT(*),SUM(SAL),DEPTNO
-- FROM SCOTT.EMP
-- WHERE JOB='SALESMAN'
-- GROUP BY DEPTNO;

-- 21] WAQTD NUMBER OF EMP’S WITH THEIR MAX SALARIES IN EACH 
-- JOB. 
-- SELECT COUNT(*),MAX(SAL),JOB 
-- FROM SCOTT.EMP
-- GROUP BY JOB;

-- 22] WAQTD NUMBER OF TIMES EACH SALARIES ARE PRESENT  IN EMP 
-- TABLE.
-- SELECT COUNT(*) NO_OF_TIMES,SAL
-- FROM SCOTT.EMP
-- GROUP BY SAL;

-- 23] WAQTD NUMBER OF EMP’S WORKING IN EACH DEPT HAVING AT 
-- LEAST 2 EMP’S IN EACH DEPT.
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- GROUP BY DEPTNO
-- HAVING COUNT(*) >= 2;

-- 24] WAQTD AVG SAL, MAX SAL, MIN SAL OF EMPS WORKING IN EACH 
-- JOB IF EMP'S HIRED AFTER 1980.
-- SELECT AVG(SAL),MAX(SAL),MIN(SAL),JOB 
-- FROM SCOTT.EMP
-- WHERE HIREDATE>'31-DEC-80'
-- GROUP BY JOB;

-- 25] WAQTD NUMBER OF EMP'S EARNING MORE THAN 2000 IN EACH 
-- DEPARTMENT WHO HIRED IN THE YEAR 1987. 
-- SELECT COUNT(*),DEPTNO
-- FROM SCOTT.EMP
-- WHERE SAL>2000 AND
--     HIREDATE LIKE '%87'
-- GROUP BY DEPTNO;


