-- 1] WAQTD THE SALARIES IN ASCENDING ORDER. 
-- SELECT SAL
-- FROM SCOTT.EMP 
-- ORDER BY SAL ASC;

-- 2] WAQTD THE SALARIES IN DESCENDING ORDER. 
-- SELECT SAL
-- FROM SCOTT.EMP 
-- ORDER BY SAL DESC;

-- 3] WAQTD THE NAMES IN ASCENDING ORDER.
-- SELECT ENAME
-- FROM SCOTT.EMP 
-- ORDER BY ENAME ASC;

-- 4] WAQTD THE NAMES IN DESCENDING ORDER
-- SELECT ENAME
-- FROM SCOTT.EMP 
-- ORDER BY ENAME DESC;

-- 5] WAQTD THE ANNUAL SALARIES IN ASCENDING ORDER. 
-- SELECT SAL*12 ANNUAL_SAL
-- FROM SCOTT.EMP
-- ORDER BY ANNUAL_SAL ASC;

-- 6] WAQTD THE ANNUAL SALARIES IN DESCENDING ORDER.
-- SELECT SAL*12 ANNUAL_SAL
-- FROM SCOTT.EMP
-- ORDER BY ANNUAL_SAL DESC;

-- 7] WAQTD THE HALFTERM SALARIES IN ASCENDING ORDER.
-- SELECT SAL*6 HALF_TERM_SAL
-- FROM SCOTT.EMP
-- ORDER BY HALF_TERM_SAL ASC;

-- 8] WAQTD THE HALFTERM SALARIES IN DESCENDING ORDER. 
-- SELECT SAL*6 HALF_TERM_SAL
-- FROM SCOTT.EMP
-- ORDER BY HALF_TERM_SAL DESC;

-- 9] WAQTD NAMES OF AS EMP WHO ARE EARNING LESS THAN 
-- 1200 RPS IN ASCENDING ORDER. 
-- SELECT ENAME 
-- FROM SCOTT.EMP 
-- WHERE SAL<1200
-- ORDER BY ENAME ASC;

-- 10] WAQTD DIFFERENT DESIGNATIONS IN EMP TABLE IN 
-- ASCENDING ORDER. 
-- SELECT DISTINCT JOB
-- FROM SCOTT.EMP
-- ORDER BY JOB;

-- 11] WAQTD NAMES OF AN EMP WORKING AS 'SALESMAN' OR 
-- 'PRESIDENT' IN DEPT NO 20 OR 30 & HIRED AFTER 1980 & HE GETS 
-- COMMISSION MORE THAN 300 RPS & HIS NAME MUST HAVE 3RD 
-- CHAR AS 'R' & PRINT HIS NAME IN DESCENDING ORDER. 
-- SELECT ENAME 
-- FROM SCOTT.EMP
-- WHERE JOB IN ('SALESMAN','PRESIDENT') AND
--         DEPTNO IN (20,30) AND
--         HIREDATE > '31-DEC-80' AND
--         COMM > 300 AND 
--         ENAME LIKE '__R%'
-- ORDER BY ENAME DESC;

-- 12] WAQTD THE 35% HIKE SALARY  FOR ALL THE EMP'S IN 
-- ASCENDING ORDER. 
-- SELECT SAL*1.35 "35% HIKE SAL"
-- FROM SCOTT.EMP
-- ORDER BY "35% HIKE SAL" ASC;

-- 13] WAQTD 49% DEDUCTION IN ANNUAL SALARY FOR ALL THE 
-- EMP'S IN DESCENDING ORDER.
-- SELECT SAL*0.51 "49% DEDUCTION SAL"
-- FROM SCOTT.EMP
-- ORDER BY "49% DEDUCTION SAL" DESC;

-- 14] WAQTD NAMES OF EMP EARNING MAXIMUM SALARY TO 
-- MINIMUM SALARY IN PROPER ORDER. 
-- SELECT ENAME
-- FROM SCOTT.EMP 
-- ORDER BY SAL DESC;

-- 15] WAQTD 32% HIKE IN HALF TERM SALARY FOR ALL THE EMP'S 
-- IN DESCENDING MANNER.
-- SELECT (SAL*6)*1.32 "32% HIKE IN HALFTERM SAL"
-- FROM SCOTT.EMP
-- ORDER BY "32% HIKE IN HALFTERM SAL" DESC;
