-- 1] WAQTD DETAILS OF AN EMP EARNING LESS THAN 'KING' 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE SAL < (SELECT SAL
--                 FROM SCOTT.EMP
--                 WHERE ENAME = 'KING');

--2] WAQTD DETAILS OF EMP’S WHO ARE WORKING IN SAME DESIGNATION
-- AS THAT OF ‘FORD’.
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE JOB IN (SELECT JOB 
--                 FROM SCOTT.EMP
--                 WHERE ENAME = 'FORD');

-- 3] WAQTD DETAILS OF EMP’S WHO ARE WORKING IN SAME DEPT AS THAT 
-- OF KING. 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE DEPTNO IN (SELECT DEPTNO 
--                 FROM SCOTT.EMP
--                 WHERE ENAME = 'KING');

-- 4] WAQTD DETAILS OF EMP’S HIRED AFTER ‘WARD’. 
-- 11 ROWS SELECTED 
-- SELECT * 
-- FROM SCOTT.EMP
-- WHERE HIREDATE > (SELECT HIREDATE
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'WARD');

-- 5] WAQTD NAMES OF AN EMP WORKING AS SALESMAN & EARNING LESS 
-- THAN MARTIN.
-- NO ROWS SELECTED 
-- SELECT ENAME
-- FROM SCOTT.EMP
-- WHERE JOB IN ('SALESMAN') AND
--         SAL < (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'MARTIN');

-- 6] WAQTD DETAILS OF EMP’S WHO ARE EARNING MORE THAN ‘JAMES’ & 
-- LESS THAN ‘JONES’.   
-- 8 ROWS SELECTED 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE SAL > (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'JAMES') AND
--     SAL < (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'JONES');

-- 7] WAQTD NAMES OF EMP & SAL OF THE EMPS EARNING LESS THAN KING. 
-- 13 ROWS SELECTED 
-- SELECT ENAME,SAL
-- FROM SCOTT.EMP
-- WHERE SAL < (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'KING');

-- 8] WAQTD NAMES OF EMP & SAL OF THE EMPS EARNING LESS THAN 
-- ADAMS 
-- ENAME             
-- SAL ---------- ---------- 
-- SMITH             
-- 800 
-- JAMES             
-- 950 
-- SELECT ENAME,SAL
-- FROM SCOTT.EMP
-- WHERE SAL < (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'ADAMS');

-- 9] WAQTD NAME & DEPTNO OF THE EMP IF THEY ARE WORKING IN THE 
-- SAME DEPT AS JONES.  
-- SELECT ENAME,DEPTNO
-- FROM SCOTT.EMP
-- WHERE DEPTNO IN (SELECT DEPTNO
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'JONES');

-- 10] WAQTD NAME & JOB OF ALL THE EMP’S WORKING IN THE SAME 
--DESIGNATION AS JAMES
--  JOB ---------- -------- 
-- MILLER    
--  CLERK 
-- JAMES      CLERK 
-- ADAMS      CLERK 
-- SMITH      
-- CLERK
-- SELECT ENAME,JOB
-- FROM SCOTT.EMP
-- WHERE JOB IN (SELECT JOB
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'JAMES');

-- 11] WAQTD EMPNO & ENAME ALONG WITH ANNUAL SAL OF ALL THE EMPS 
-- IF THEIR ANNUAL SAL IS GREATER THAN ‘WARD’ ANNUAL SAL. 
-- SELECT EMPNO,ENAME,SAL*12 AS ANNUAL_SAL
-- FROM SCOTT.EMP
-- WHERE SAL*12 > (SELECT SAL*12
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'WARD');

-- 12] WAQTD NAME & HIREDATE OF EMP’S IF THEY HIRED BEFORE TURNER. 
-- SELECT ENAME,HIREDATE
-- FROM SCOTT.EMP
-- WHERE HIREDATE < (SELECT HIREDATE
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'TURNER');

-- 13] WAQTD NAME & HIREDATE OF EMP’S IF THEY ARE HIRED AFTER 
-- PRESIDENT. 
-- SELECT ENAME,HIREDATE
-- FROM SCOTT.EMP
-- WHERE HIREDATE > (SELECT HIREDATE
--                     FROM SCOTT.EMP
--                     WHERE JOB IN ('PRESIDENT'));

-- 14] WAQTD NAME & SAL OF EMPS IF THEY ARE EARNING SAL LESS THAN 
-- THE EMP WHOSE EMPNO IS 7839. 
-- 13 ROWS SELECTED 
-- SELECT ENAME,SAL
-- FROM SCOTT.EMP
-- WHERE SAL < (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE EMPNO IN (7839));

-- 15] WAQTD DETAILS OF EMP IF EMP IS HIRED BEFORE MILLER. 
-- 11 ROWS SELECTED 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE HIREDATE < (SELECT HIREDATE
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'MILLER');

-- 16] WAQTD DETAILS OF EMP WHO EARNS MORE THAN ALLEN. 
-- 6 ROWS SELECTED 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE SAL > (SELECT SAL
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'ALLEN');

-- 17] WAQTD NUMBER OF EMP’S HIRED AFTER KING. 
-- COUNT(*) -------- 
-- 5  
-- SELECT COUNT(*)
-- FROM SCOTT.EMP
-- WHERE HIREDATE > (SELECT HIREDATE
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'KING');

-- 18] WAQTD TOTAL SAL GIVEN TO EMP’S WORKING IN SAME DEPT AS THAT 
-- OF ‘WARD’. 
-- SUM(SAL) -------- 
-- 9400
-- SELECT SUM(SAL)
-- FROM SCOTT.EMP
-- WHERE DEPTNO IN (SELECT DEPTNO
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'WARD');

-- 19] WAQTD DETAILS OF EMP WORKING IN DEPT NO 20 & WORKING IN 
-- SAME DESIGNATION AS THAT OF SMITH. 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE DEPTNO IN (20) AND
--      JOB IN (SELECT JOB
--                     FROM SCOTT.EMP
--                     WHERE ENAME = 'SMITH');

-- 20] WAQTD ENAME & SAL OF EMP’S WHO ARE EARNING MORE THAN 
-- MILLER BUT LESS THAN ALLEN. 
-- ENAME             
-- SAL ---------- ---------- 
-- TURNER           
-- 1500
-- SELECT ENAME,SAL
-- FROM SCOTT.EMP
-- WHERE SAL > (SELECT SAL
-- FROM SCOTT.EMP
--     WHERE ENAME = 'MILLER') AND 
--     SAL < (SELECT SAL
--     FROM SCOTT.EMP
--     WHERE ENAME = 'ALLEN');

-- 21] WAQTD ENAME & SAL OF ALL THE EMPS WHO ARE EARNING MORE 
-- THAN 1000 BUT LESS THAN 3000. 
-- 9 ROWS SELECTED
-- SELECT ENAME,SAL
-- FROM SCOTT.EMP
-- WHERE SAL > 1000 AND SAL < 3000;

-- 22] WAQTD ALL THE DETAILS OF EMP WORKING IN DEPT NO 20 & WORKING 
-- IN SAME DESIGNATION AS SMITH. 
--   7876 ADAMS      CLERK           7788 23-MAY-87       1100                    20 
--   7369 SMITH      CLERK           7902 17-DEC-80        800                    20 
--  SELECT *
--  FROM SCOTT.EMP
--  WHERE DEPTNO IN (20) AND JOB IN (SELECT JOB
--                                     FROM SCOTT.EMP
--                                     WHERE ENAME = 'SMITH');

-- 23] WAQTD DETAILS OF EMP WORKING AS MANAGER IN THE SAME DEPT AS 
-- TURNER. 
--   EMPNO ENAME      JOB              MGR HIREDATE         SAL       COMM     
-- DEPTNO ------- ---------- --------- ---------- --------- ---------- ---------- ---------- 
--    7698 BLAKE      MANAGER         7839 01-MAY-81       2850                    30 
-- SELECT *
-- FROM SCOTT.EMP
-- WHERE JOB IN ('MANAGER') AND DEPTNO IN (SELECT  DEPTNO 
--                                         FROM SCOTT.EMP
--                                         WHERE ENAME = 'TURNER');
 
-- 24] WAQTD NAME & HIREDATE OF EMP’S HIRED AFTER 1980 & BEFORE 
-- KING. 
--  7 ROWS SELECTED 
-- SELECT ENAME,HIREDATE
-- FROM SCOTT.EMP
-- WHERE HIREDATE > '31-DEC-80' AND HIREDATE < (SELECT HIREDATE
--                                             FROM SCOTT.EMP
--                                             WHERE ENAME = 'KING')
 
-- 25] WAQTD NAME & SAL ALONG WITH ANNUAL SAL FOR ALL EMP’S WHOSE 
-- SAL IS LESS THAN BLAKE OR EMP’S EARNING MORE THAN 3500. 
--  10 ROWS SELECTED
-- SELECT ENAME,SAL,SAL*12 AS ANNUAL_SAL
-- FROM SCOTT.EMP
-- WHERE SAL < (SELECT SAL
--             FROM SCOTT.EMP
--             WHERE ENAME='BLAKE') OR SAL > 3500;

